Добавляет разметку страницы index
htmlacademy-htmlcss/1578925-technomart-30 pull request #2
Opened 2021-01-25 04:41 UTC by ZKseniya

2021-01-25 04:44 UTC, ZKseniya commented on index.html
> +          </div>
Сомневаюсь в выборе данного решения. Пример нашла в интернете

2021-01-25 18:11 UTC, andreysgra requested changes
1. Есть проблемы с валидацией HTML. Часть из них я описал в комментариях. Остальное проверьте [здесь](https://validator.w3.org/nu/#textarea) и устраните ошибки.
2. Есть проблемы с наименованием файлов (критерий [Б14](https://up.htmlacademy.ru/htmlcss/30/criteries#b14))

![image](https://user-images.githubusercontent.com/17790771/105745772-b34aa200-5f4f-11eb-927c-38c8ee2ff07e.png)

Нужно привести название файлов в соответствие с критерием. (Есть один нюанс - git игнорирует регистр букв в названиях файлов, если нет иных изменений. То есть, если вы переименуете файл **Object_1.jpg** в **object_1.jpg**, то после коммита всё равно останется **Object_1.jpg**. Как вариант решения - дать другое имя, например **object-1.jpg**.
3. Есть проблемы с форматированием кода (критерий [Б15](https://up.htmlacademy.ru/htmlcss/30/criteries#b15))

![image](https://user-images.githubusercontent.com/17790771/105746501-8f3b9080-5f50-11eb-8015-4fef96532733.png)

Использованы разные символы для отступов (чёрточки - это Tab, точки - это Space). Нужно всё привести к одному типу. Как сделать: в редакторе кода (лучше, если это VS Code или Atom) установить плагин editorconfig (тогда редактор в дальнейшем будет брать настройки из файла конфигурации, который есть в вашем проекте) и установить плагин beautify, который форматирует код (горячие клавиши для него: VS Code - `Alt+Shift+F`, Atom - `Ctrl + Alt + B`

Немного про настройки редакторов можно посмотреть здесь: [Atom](https://docs.google.com/document/d/1Zv55waarUDzfbckaJuO6Q2hyY0lrvqfAQqEJ3DbBQ1I/edit?usp=sharing), [VS Code](https://docs.google.com/document/d/1qvNDOPDe_u9vENMPcmUwzwxChfTl6sXaVg1fYvwzI3k/edit?usp=sharing)

2021-01-27 19:35 UTC, andreysgra approved these changes

2021-01-27 19:35 UTC, andreysgra commented on index.html
> +            <img src="img/catalog/Object_1.jpg" alt="BOSCHBFG 9000">
Исправьте названия файлов картинок в карточках.

2021-01-27 19:35 UTC, merged