Делает грид-сетку на главной странице
htmlacademy-htmlcss/1578925-technomart-30 pull request #7
Opened 2021-02-09 08:35 UTC by ZKseniya

2021-02-09 08:42 UTC, ZKseniya commented on index.html
>        <div class="promo-slider">
Слайдер переверстала на дивах, чтобы было проще делать сетку на гридах

2021-02-09 17:22 UTC, andreysgra requested changes
Ну а в целом всё замечательно. Видно, что технологию grid вы понимаете и используете по назначению.

2021-02-09 17:22 UTC, andreysgra commented on css/style.css
>  }
Нужно ещё добавить паддинги по краям: `padding: 0 10px`. Паддинги нужны для того, чтобы на минимальном разрешении экрана (для данного макета это 960px - [Б13](https://up.htmlacademy.ru/htmlcss/30/criteries#b13)) контент не прилипал к краям экрана.

2021-02-09 17:22 UTC, andreysgra commented on css/style.css
> +}
У списков есть дефолтный паддинг слева `padding-left`:

![image](https://user-images.githubusercontent.com/17790771/107400226-ab276080-6b12-11eb-9720-bd91f108fb65.png)

Этот отступ, как правило не нужен и его надо обнулить.

2021-02-09 17:22 UTC, andreysgra commented on css/style.css
> +  height: 409px;
Не стоит задавать фиксированное значение высоты у блоков, в которых контент может измениться. В противном случае тест на переполнение не пройдёт. Лучше использовать свойство `min-height`.

2021-02-09 17:22 UTC, andreysgra commented on css/style.css
> +  grid-template-rows: repeat(3, 1fr);
Шаблон сетки в этом блоке можно упростить. Посмотрите [пример](https://codepen.io/angra/pen/VbpZjE).

2021-02-09 17:22 UTC, andreysgra commented on css/style.css
> +  grid-template-rows: 200px;
Аналогично, как и с фиксированным значением свойства `height` - если вы явно зададите высоту ряда, то при увеличении контента он просто выйдет за пределы блока. Использовать фиксированное значение для ` grid-template-rows` стоит только в том случае, если контент блока не должен изменяться.

2021-02-11 18:33 UTC, andreysgra requested changes

2021-02-11 18:33 UTC, andreysgra commented on css/style.css
> +  grid-row: 1 / 2;
Не нашёл grid-контейнера, которому бы принадлежал этот grid-элемент. А если нет grid-контейнера, то и эти свойства не нужны.

2021-02-11 18:33 UTC, andreysgra commented on css/style.css
> +  grid-row: 2 / 3;
Не нашёл grid-контейнера, которому бы принадлежал этот grid-элемент.

2021-02-11 18:33 UTC, andreysgra commented on css/style.css
> +  grid-column: 1 / 2;
Необходимости в этом свойстве нет, так как колонка в фильтре одна.

2021-02-11 18:33 UTC, andreysgra commented on css/style.css
> +  grid-template-columns: auto auto auto 1fr;
Данный шаблон для колонок не подходит, так как ссылок на страницы может быть больше:

![image](https://user-images.githubusercontent.com/17790771/107681438-19555a00-6cb0-11eb-835b-70e49eb56f97.png)

Здесь нужно использовать `auto-fit` -> `repeat(auto-fit,minmax(38px,max-content))`, либо сделать раскладку на флексах.

2021-02-17 09:49 UTC, merged